# This is a config file which containts all the data directories and other parameters. Modify this file to your home
# directories to run the code
params = {
    'ZOTERO_LOC' : '/Users/jhatkins/Zotero/storage',
    'PDF_LOC' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/pdfs/',
    'TEXT_LOC': '/Users/jhatkins/PycharmProjects/label_PDFs/data/text/',
    'JSON_LOC': '/Users/jhatkins/PycharmProjects/label_PDFs/data/json/',
    'PREPROC_LOC' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/preprocessed/',
    'MODEL_LOC' : '/Users/jhatkins/PycharmProjects/label_PDFs/NER/project/model/model.tar.gz',
    'JAR_LOC' : 'Users/jhatkins/PycharmProjects/label_PDFs/NER/project/model/stanford-corenlp-4.2.0-models-english.jar',
    'VARIABLES_CSV': '/Users/jhatkins/PycharmProjects/label_PDFs/data/csv/variables.csv',
    'MISSIONS_CSV' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/csv/missions.csv',
    'INSTRUMENTS_CSV' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/csv/instruments.csv',
    'LOCATIONS_CSV' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/csv/locations.csv',
    'EXCEPTION_CSV' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/csv/exceptions.csv',
    'ZOTERO_NOTES_FILE' : '/Users/jhatkins/PycharmProjects/label_PDFs/data/json/zot_notes.json',
    'USER_LIBRARY_KEY' : '6657757',
    'GROUP_LIBRARY_KEY' : '2395775',
    'USER_COLLECTION_ID' : 'H244E5IH',
    'MLS_COLLECTION_ID' : 'F3P68PWK',
    'SCOPUS_COLLECTION_ID' : 'QJR2GCH8',
    'ZOTERO_API_KEY' : 'tB3q3dduZDZR1xXOXGw9ngvV',
    'LOAD_JSON' : True,
    'TEST_CASE' : True,
    'REMOVE_STOPWORDS' : False,
    'PARAGRAPH_LABELS' : ["Abstract", "Data", "MLS", "Aura", "Methods", "Instruments",
                          "Measurements"],
    'RAND_SEED' : 714,
    'SUBPROC' : 4
}
